"""Auto-generated by gemini-hub export (2026-09-09 17:40). 직접 편집 금지.

재생성:  python -m gemini_hub.cli export --out C:\\python\\github_actions\\tsc-bot\\hub_loader.py

이 모듈은 외부 의존성 없이(stdlib + google-genai) 동작하는 자체완결 로더다.
- TEXT_CANDIDATES : 정적 기본/폴백 후보 (본판→축소판, gemini→gemma, 버전 내림차순)
- 자동발견(AUTO_DISCOVER) : complete() 호출마다 ListModels로 카탈로그를 조회해
  include/exclude 패턴에 맞는 모델을 후보로 자동 편입한다 (신규 모델 무수정 추적).
  발견 실패 시 정적 TEXT_CANDIDATES로 폴백.
"""

import fnmatch
import json
import os
import urllib.request

TEXT_CANDIDATES = ['gemini-3.7-flash', 'gemini-3.6-flash', 'gemini-3.5-flash', 'gemini-2.5-flash', 'gemma-4-31b-it', 'gemini-3.5-flash-lite', 'gemini-3.1-flash-lite', 'gemini-3.1-flash-lite-preview', 'gemini-2.5-flash-lite', 'gemma-4-26b-a4b-it']

OPENROUTER_FALLBACK = ['google/gemma-4-31b-it:free', 'nvidia/nemotron-3-ultra-550b-a55b:free', 'thinkingmachines/inkling-small:free']

AUTO_DISCOVER = True
INCLUDE_PATTERNS = ['gemini-*flash*', 'gemma-*']
EXCLUDE_PATTERNS = ['*preview*', '*pro*', '*omni*', '*robotics*', '*computer-use*', '*latest*', '*embedding*', '*image*', 'aqa']
OR_MODE_AUTO = True
FAMILY_ORDER = ['gemini', 'gemma']
REDUCED_LAST = True
REDUCED_PATTERNS = ['*lite*', '*mini*', '*nano*', '*-8b*', '*-4b*', '*-2b*', '*-1b*', '*-a[0-9]b*', '*-a[0-9][0-9]b*']

_OR_CATALOG_URL = "https://openrouter.ai/api/v1/models"


def _openrouter_free_ids(top_n=5):
    """OpenRouter 카탈로그에서 무료 텍스트 모델 ID 실시간 선정 (stdlib 전용)."""
    req = urllib.request.Request(_OR_CATALOG_URL)
    with urllib.request.urlopen(req, timeout=20) as resp:
        data = json.loads(resp.read().decode("utf-8")).get("data", [])
    bad = ("preview", "lyria", "imagen", "veo")
    scored = []
    for m in data:
        mid = m.get("id", "")
        p = m.get("pricing") or {}
        arch = m.get("architecture") or {}
        try:
            if float(p.get("prompt", "1")) != 0 or \
                    float(p.get("completion", "1")) != 0:
                continue
        except (TypeError, ValueError):
            continue
        ins = arch.get("input_modalities") or ["text"]
        outs = arch.get("output_modalities")
        if "text" not in ins:
            continue
        if outs and "text" not in outs:
            continue
        if any(b in mid.lower() for b in bad):
            continue
        scored.append((m.get("context_length") or 0, mid))
    scored.sort(reverse=True)
    return [mid for _, mid in scored[:top_n]]


def _or_candidate_ids():
    """auto 모드: 카탈로그 실시간 선정 우선, 실패 시 정적 리스트."""
    if OR_MODE_AUTO:
        try:
            ids = _openrouter_free_ids()
            if ids:
                print(f"[hub_loader] or-auto: {len(ids)} free models "
                      f"(1st={ids[0]})")
                for mid in OPENROUTER_FALLBACK:
                    if mid not in ids:
                        ids.append(mid)
                return ids
            print("[hub_loader] or-auto: free 0 — static fallback")
        except Exception as e:  # noqa: BLE001
            print(f"[hub_loader] or-catalog skipped: {str(e)[:100]}")
    return list(OPENROUTER_FALLBACK)


def _is_reduced(low):
    rest = "-" + (low.split("-", 1)[1] if "-" in low else low)
    return any(fnmatch.fnmatchcase(rest, p.lower()) for p in REDUCED_PATTERNS)


def _parse_key(name):
    low = str(name).lower()
    tier = 1 if (REDUCED_LAST and _is_reduced(low)) else 0
    family = len(FAMILY_ORDER)
    for i, fam in enumerate(FAMILY_ORDER):
        if low.startswith(fam.lower()):
            family = i
            break
    nums = tuple(-int(n) for n in __import__("re").findall(r"\d+", str(name)))
    return tier, family, nums


def _sort_candidates(cands):
    indexed = list(enumerate(cands))
    indexed.sort(key=lambda t: (_parse_key(t[1]), t[0]))
    return [name for _, name in indexed]


def _match(name, patterns):
    return any(fnmatch.fnmatch(name, p) for p in patterns)


def text_candidates():
    """자동발견(실시간) + 정적 후보 병합. env 강제(GEMINI_MODEL_PRIMARY) 최우선."""
    discovered = []
    if AUTO_DISCOVER:
        try:
            from google import genai
            client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
            catalog = [m.name.replace("models/", "") for m in client.models.list()]
            discovered = _sort_candidates(
                n for n in catalog
                if _match(n, INCLUDE_PATTERNS) and not _match(n, EXCLUDE_PATTERNS))
            print(f"[hub_loader] auto-discover: {len(discovered)} models "
                  f"(1st={discovered[0] if discovered else '-'})")
        except Exception as e:  # noqa: BLE001
            print(f"[hub_loader] auto-discover skipped: {str(e)[:100]}")

    cands = _sort_candidates(
        discovered + [m for m in TEXT_CANDIDATES if m not in discovered])

    forced = os.environ.get("GEMINI_MODEL_PRIMARY", "").strip()
    if forced:
        if forced in cands:
            cands.remove(forced)
        cands.insert(0, forced)
    return cands


def complete(prompt, system_instruction="", temperature=None):
    """후보를 순회하며 첫 성공 응답을 반환. 전부 실패 시 RuntimeError."""
    from google import genai
    from google.genai import types

    errors = []
    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])

    throttled = set()  # 실행 중 429/503 본 모델 재시도 방지
    for model_id in text_candidates():
        if model_id in throttled:
            continue
        kwargs = {}
        if system_instruction:
            kwargs["system_instruction"] = system_instruction
        if temperature is not None:
            kwargs["temperature"] = temperature
        try:
            resp = client.models.generate_content(
                model=model_id, contents=prompt,
                config=types.GenerateContentConfig(**kwargs),
            )
            text = (resp.text or "").strip()
            if not text:
                raise RuntimeError("빈 응답")
            return text
        except Exception as e:  # noqa: BLE001
            msg = str(e)
            errors.append(f"[gemini] {model_id}: {msg[:140]}")
            print(f"[hub_loader] {model_id} 실패: {msg[:120]}")
            up = msg.upper()
            if ("429" in msg or "RESOURCE_EXHAUSTED" in up
                    or "503" in msg or "UNAVAILABLE" in up
                    or "OVERLOADED" in up or "404" in msg or "NOT_FOUND" in up):
                throttled.add(model_id)

    api_key = os.environ.get("OPENROUTER_API_KEY", "").strip()
    if api_key:
        for model_id in _or_candidate_ids():
            payload = json.dumps({
                "model": model_id,
                "messages": ([{"role": "system",
                               "content": system_instruction}]
                              if system_instruction else [])
                              + [{"role": "user", "content": prompt}],
                "temperature": temperature if temperature is not None else 0.4,
            }).encode("utf-8")
            req = urllib.request.Request(
                "https://openrouter.ai/api/v1/chat/completions",
                data=payload,
                headers={"Authorization": f"Bearer {api_key}",
                          "Content-Type": "application/json"},
            )
            try:
                with urllib.request.urlopen(req, timeout=90) as resp:
                    data = json.loads(resp.read().decode("utf-8"))
                return data["choices"][0]["message"]["content"].strip()
            except Exception as e:  # noqa: BLE001
                errors.append(f"[openrouter] {model_id}: {str(e)[:140]}")
                print(f"[hub_loader] or:{model_id} 실패: {str(e)[:120]}")

    raise RuntimeError("hub_loader: 모든 후보 실패\n" + "\n".join(errors))
